// Auto-generated by LibreLane
module decoder(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input ena_i,
  input[7:0] input_ni,
  output[255:0] output_o,
  output[255:0] output_no
);
endmodule
